
import { Card } from "@/core/objects/item/Subclass/Card"
import { ItemMap } from "@/core/objects/item/Item"

export type CardMap = ItemMap & {
    status:{
        cost:number|null
    }
    entry?:string[],
    tags?:string[],  // 卡牌标签（用于分类和筛选）
}

const cardList:CardMap[] = [{
    label:"打击",
    tags:["attack", "basic"],
    status:{
        damage:5,
        cost:1,
    },
    describe:[
        "造成",{key:["status","damage","value"]},"点伤害"
    ],
    key:"original_card_00001",
    interaction:{
        use:{
            target:{faction:"enemy"},
            effects:[{
                key:"damage",
                params:{value:5},
            }]
        }
    }
},{
    label:"消耗打击",
    tags:["attack"],
    status:{
        damage:15,
        cost:1,
    },
    entry:["exhaust"],
    describe:[
        "造成",{key:["status","damage"]},"点伤害"
    ],
    key:"original_card_00002",
    interaction:{
        use:{
            target:{faction:"enemy"},
            effects:[{
                key:"damage",
                params:{value:15},
            }]
        }
    }
},{
    label:"虚无打击",
    tags:["attack"],
    status:{
        damage:15,
        cost:1,
    },
    entry:["void"],
    describe:[
        "造成",{key:["status","damage"]},"点伤害"
    ],
    key:"original_card_00003",
    interaction:{
        use:{
            target:{faction:"enemy"},
            effects:[{
                key:"damage",
                params:{value:15},
            }]
        }
    }
},{
    label:"固有打击",
    tags:["attack"],
    status:{
        damage:8,
        cost:1,
    },
    entry:["inherent"],
    describe:[
        "造成",{key:["status","damage"]},"点伤害"
    ],
    key:"original_card_00012",
    interaction:{
        use:{
            target:{faction:"enemy"},
            effects:[{
                key:"damage",
                params:{value:8},
            }]
        }
    }
},{
    label:"肌肉强化",
    tags:["power"],
    status:{
        power:1,
        cost:0
    },
    entry:["exhaust"],
    describe:["获得",{key:["status","power"]},"层力量"],
    key:"original_card_00004",
    interaction:{
        use:{
            target:{faction:"player",key:"self"},
            effects:[{
                key:"applyState",
                params:{stateKey:"power",stacks:1},
            }]
        }
    }
},{
    label:"淬毒",
    tags:["skill"],
    status:{
        poison:3,
        cost:1
    },
    describe:["使目标获得",{key:["status","poison"]},"层中毒"],
    key:"original_card_00008",
    interaction:{
        use:{
            target:{faction:"enemy"},
            effects:[{
                key:"applyState",
                params:{stateKey:"poison",stacks:3},
            }]
        }
    }
},{
    label:"随机打击",
    tags:["attack"],
    status:{
        cost:1,
        minDamage:5,
        maxDamage:10
    },
    describe:["造成",{key:["status","minDamage"]},"到",{key:["status","maxDamage"]},"点随机伤害"],
    key:"original_card_00009",
    interaction:{
        use:{
            target:{faction:"enemy"},
            effects:[{
                key:"damage",
                params:{value:"$random[5,10]"},
            }]
        }
    }
},{
    label:"虚弱诅咒",
    tags:["curse"],
    status:{
        weak:2,
        cost:0
    },
    describe:["使自己获得",{key:["status","weak"]},"层虚弱"],
    key:"original_card_00010",
    interaction:{
        use:{
            target:{faction:"player",key:"self"},
            effects:[{
                key:"applyState",
                params:{stateKey:"weak",stacks:2},
            }]
        }
    }
},{
    label:"易伤打击",
    tags:["attack"],
    status:{
        vulnerable:2,
        damage:8,
        cost:1
    },
    describe:["造成",{key:["status","damage"]},"点伤害，使目标获得",{key:["status","vulnerable"]},"层易伤"],
    key:"original_card_00011",
    interaction:{
        use:{
            target:{faction:"enemy"},
            effects:[{
                key:"damage",
                params:{value:8},
            },{
                key:"applyState",
                params:{stateKey:"vulnerable",stacks:2},
            }]
        }
    }
},{
    label:"旋风斩",
    tags:["attack"],
    status:{
        cost:1,
        damage:3
    },
    describe:["对敌方全体造成",{key:["status","damage"]},"点伤害"],
    key:"original_card_00005",
    interaction:{
        use:{
            target:{number:"all"},//阵营默认为敌人
            effects:[{
                key:"damage",
                params:{value:3},
            }]
        }
    }
},{
    label:"末日",
    tags:["attack"],
    status:{
        cost:3,
        damage:999,
    },
    describe:["对所有人造成",{key:["status","damage"]},"点伤害"],
    key:"original_card_00006",
    interaction:{
        use:{
            target:{faction:"all",number:"all"},
            effects:[{
                key:"damage",
                params:{value:999},
            }]
        }
    }
},{
    label:"接二连三",
    tags:["attack"],
    status:{
        cost:1,
        damage:2,
    },
    describe:["对至多3个敌人造成",{key:["status","damage"]},"点伤害"],
    key:"original_card_00007",
    interaction:{
        use:{
            target:{faction:"enemy",number:3},
            effects:[{
                key:"damage",
                params:{value:2},
            }]
        }
    }
}]

export function getCardByKey(key:string){
    const data = cardList.find(value=>value.key == key)
    if(!data)throw new Error("不存在的卡牌")
    const card = new Card(data)
    return card
}

export function getAllCards(){
    return cardList
}